services:

  angular:
    build: ./app
    ports:
      - "4200:8080"
    depends_on:
      - api
  
  api:
    build: ./api
    ports:
      - "8080:8080"
    depends_on:
      - db
    
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: macronomicon
      MYSQL_USER: root
      MYSQL_PASSWORD: CompSQLD2024!
      MYSQL_ROOT_PASSWORD: CompSQLD2024!
    volumes:
      - database_data:/var/lib/mysql
      - ./api/init.sql:/tmp/init.sql
    command: --init-file /tmp/init.sql

volumes:
  database_data: