services:

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    networks:
      - appnet
    environment:
      MYSQL_DATABASE: 'macronomicon'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - database_data:/var/lib/mysql
      - ./api/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./api/my.cnf:/etc/mysql/conf.d/my.cnf
    command: --init-file=/docker-entrypoint-initdb.d/init.sql

  api:
    restart: always
    build: ./api
    ports:
      - "8080:8080"
    networks:
      - appnet
    depends_on:
      - db
    environment:
      DB_USERNAME: 'user'
      DB_PASSWORD: 'password'
      DB_NAME: 'macronomicon'
      DB_HOST: 'db'
      DB_PORT: 3306
    
  angular:
    build: ./app
    ports:
      - "4200:4200"
    links:
      - api
    networks:
      - appnet
    depends_on:
      - api

networks:
  appnet:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"

volumes:
  database_data: