version: '3'

services:

  angular:
    build: ./app
    ports:
      - "4200:4200"
    volumes:
      - .:/app
    command: npm start
    depends_on:
      - api
  
  api:
    build: ./api
    ports:
      - "8080:8080"
    volumes:
      - .:/api
    command: npm start
    depends_on:
      - db
    
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: CompSQLD2024!
      MYSQL_DATABASE: macronomicon
      MYSQL_USER: root
      MYSQL_PASSWORD: CompSQLD2024!
    volumes:
      - ./db:/var/lib/mysql