services:

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    networks:
      - appnet
    environment:
      MYSQL_DATABASE: macronomicon
      MYSQL_USER: root
      MYSQL_PASSWORD: CompSQLD2024!
      MYSQL_ROOT_PASSWORD: CompSQLD2024!
      MY_SQL_ROOT_HOST: '%'
    volumes:
      - database_data:/var/lib/mysql
      - ./api/init.sql:/tmp/init.sql
    command: --init-file /tmp/init.sql
  
  api:
    restart: always
    build: ./api
    ports:
      - "8080:8080"
    networks:
      - appnet
    depends_on:
      - db
    environment:
      DB_USERNAME: root
      DB_PASSWORD: CompSQLD2024!
      DB_NAME: macronomicon
      DB_HOST: db
      DB_PORT: 3306
    
  angular:
    build: ./app
    ports:
      - "4200:4200"
    networks:
      - appnet
    depends_on:
      - api

networks:
  appnet:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"

volumes:
  database_data: